import Cookies from "js-cookie";
import moment from "moment";
import Head from "next/head";
import { useCallback, useEffect, useState } from "react";
import Footer from "../../components/Footer";
import Navbar from "../../components/Navbar";
import { getData } from "../../utils/fetchData";
import { formatDate } from "../../utils/formatDate";

export default function Dashboard() {
  const [data, setData] = useState([]);
  const token = Cookies.get("token");

  const getDashboard = useCallback(async () => {
    const req = await getData("api/v1/participants/dashboard", {}, token);
    setData(req.data);
  }, []);

  useEffect(() => {
    getDashboard();
  }, []);

  return (
    <>
      <Head>
        <title>Semina | Dashboard Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="bg-navy">
        <Navbar />
      </section>

      <section className="bg-navy">
        <div className="checkout container">
          <div className="text-center checkout-title">Invest In Yourself</div>

          {data.map((item) => (
            <div className="event-details container d-flex flex-wrap justify-content-lg-center align-items-center gap-5" key={item._id}>
              <img
                src={`${process.env.NEXT_PUBLIC_API_IMAGE}/${item.historyEvent.cover}`}
                className="event-image"
                alt="semina"
              />
              <div className="d-flex flex-column gap-3">
                <h5>{item.historyEvent.title}</h5>

                <div className="d-flex align-items-center gap-3">
                  <img src="/icons/ic-marker-white.svg" alt="" />
                  <span>{item.historyEvent.venueName}</span>
                </div>
                <div className="d-flex align-items-center gap-3">
                  <img src="/icons/ic-time-white.svg" alt="" />
                  <span>{moment(item.historyEvent.date).format("HH.MM A")}</span>
                </div>
                <div className="d-flex align-items-center gap-3">
                  <img src="/icons/ic-calendar-white.svg" alt="" />
                  <span>{formatDate(item.historyEvent.date)}</span>
                </div>
              </div>
              <div className="total-price">${item.historyEvent.price}</div>
            </div>
          ))}
        </div>
      </section>

      <Footer />
    </>
  );
}
